#!/usr/bin/env ruby

require 'cloudinary'
require 'thor'

class MyCLI < Thor

  desc "list TAG", "lists all images tagged with TAG"
  def list(tag)
    puts Cloudinary::Api.resources_by_tag(tag)
  end

  desc "delete VALUE", "deletes all images"
  option :by, :enum => ['tag', 'prefix'], :required => true
  def delete(value)
    puts Cloudinary::Api.delete_resources_by_tag(value) if options[:by] == 'tag'
    puts Cloudinary::Api.delete_resources_by_prefix(value) if options[:by] == 'prefix'
  end

end



MyCLI.start(ARGV)
